management.endpoints.web.exposure.include=health
# ===============================
# Kafka runtime config (Docker)
# ===============================
spring.kafka.bootstrap-servers=kafka:9092

# Use a different group id for Docker/Jenkins
spring.kafka.consumer.group-id=notification-group-docker
spring.kafka.consumer.auto-offset-reset=latest

# ===============================
# Gmail SMTP configuration
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=debashritamandal852@gmail.com
spring.mail.password=jjjpujxrvvnrsodl

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
